#################################
#        Performance & Basics   #
#################################
backend = "glx";
vsync = true;
detect-rounded-corners = true;
detect-client-opacity = true;
detect-transient = true;
use-damage = true;

#################################
#          Animations           #
#################################
fading = true;
fade-delta = 5;                 # Smooth animation speed (ms)
fade-in-step = 0.03;            # Gentle fade-in
fade-out-step = 0.03;           # Gentle fade-out
inactive-opacity = 0.9;        # Base opacity for inactive windows
inactive-dim = 0.1;             # Subtle dimming effect

focus-exclude = [
    "class_g = 'mpv'",
    "class_g = 'vlc'",
    "class_g = 'firefox'",
    "class_g = 'Chromium'",
    "class_g = 'TelegramDesktop'",
    "class_g = 'DBeaver'",
    "class_g = 'GitHub Desktop'",
];

#################################
#          Shadows              #
#################################
shadow = true;
shadow-radius = 12;
shadow-offset-x = -8;
shadow-offset-y = -8;
shadow-opacity = 0.3;
shadow-color = "#000000"

shadow-exclude = [
    "class_g = 'Polybar'",
    "_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'",
    "name = 'Notification'",
    "class_g ?= 'Notify-osd'"
];

#################################
#        Special Windows        #
#################################
wintypes: {
    tooltip = { fade = true; shadow = false; opacity = 0.9; focus = true; };
    dock = { shadow = false; };
    desktop = { shadow = false; };
    notification = { fade = true; shadow = false; opacity = 1.0; };
    popup_menu = { opacity = 1.0; shadow = false; };
    dropdown_menu = { opacity = 1.0; shadow = false; };
    dnd = { shadow = false; };
};
